### ISSUE TITLE
Downloading?

### ISSUE THREAD

**Issue by dashriprock007** [truefedex/tv-bro#10]
I have tried a few different versions on my Firestick4k since Puffin has lost the ability to download...

I cant get anything to download? am I missing something?

**Comment by truefedex** [comment]
Please, try latest beta version. Is issue can be reproduced on it?

**Comment by dashriprock007** [comment]
What is latest beta and where can I get it?

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by truefedex** [comment]
You can find it here:
https://github.com/truefedex/tv-bro/releases
Or by selecting beta channel on tvbro settings.
Or you can signup for betatesting on Google Play (if you use regular android-based mediabox, not Android TV):
https://play.google.com/apps/testing/com.phlox.tvwebbrowser

**Comment by dashriprock007** [comment]
1.5.5 does the same... Even when I goto filelinked.com I can't download from there...

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by truefedex** [comment]
Do you mean download apk from main page of https://www.filelinked.com ? 
I checked it in tvbro and it works. Are you sure you have enough free space on your device?

**Comment by dashriprock007** [comment]
You are trying on a firestick 4k? I have over 1.5gb free space

Yes on download apk from filinked

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by truefedex** [comment]
Thank you! I can reproduce problem on my firestick (seems I not tested apk downloads on it yet). Looks like amazon specially blocking apk downloads. Other file types downloads successfully. I even found this thread:
https://forums.developer.amazon.com/questions/59150/webview-downloadlistener-not-working-on-amazon-fir.html
where an amazon developer says "Downloading APK files is disabled and not supported. This is by design.".
I will try to workaround this, but currently can not guarantee that I can fix it from TV Bro's side.

**Comment by dashriprock007** [comment]
Yes they are cracking down... Puffin used to work and yours was supposed to be the answer?

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by dashriprock007** [comment]
Using the new beta 157

How do I clear history or tabs? Can I customize a home page?

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by truefedex** [comment]
You can clear history by second menu button (with "clock") - there should be history screen where a button "clear" is.
You can clear tabs just bu closing them - buttom left button (with "cross") will close current tab. You can also close all tabs at once by long pressing on tab title - there will menu appear with "Close all" option.
Home page non-configurable but often used sites will dissappear when you clear history and restart app.

**Comment by dashriprock007** [comment]
Yes but after that homepage brings up YouTube Facebook etc

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by truefedex** [comment]
Yes, this is by design

**Comment by dashriprock007** [comment]
Boo!! :)

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by dashriprock007** [comment]
Should we be able to activate full screen on a youtube video? When I do it....it only expands to upper left corner....using beta 1.6

________________________________

**Comment by dashriprock007** [comment]
Sending this again if you didn't see my question

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by truefedex** [comment]
I also noticed this issue but seems there are no any solution from tv bro side - this bug somewhere in WebView (android built'in web rendering engine) or YouTube itself. TV Bro almost not add any additional logic regarding displaing video content. I think this is because google not testing well their web sites and webview video playback abilities on TV platforms.

**Comment by dashriprock007** [comment]
It works on silk and Firefox... Odd

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by truefedex** [comment]
Hmm really odd. I will check this problem again

**Comment by truefedex** [comment]
@dashriprock007 seems this is a bug in amazon's custom webview.
Firefox TV also stugged with this issue, but they have fixed it partly and nobody knows how:
https://github.com/mozilla-mobile/firefox-tv/issues/2170
But seems this is still reproducible even on Firefox TV in some conditions:
https://github.com/mozilla-mobile/firefox-tv/issues/2851

Seems amazon applied some sort of compulsory scaling to all apps UI. 
https://developer.amazon.com/docs/fire-tv/design-and-user-experience-guidelines.html#screen-size-and-resolution
I think this is reason of the bug. But I dont know how to fix it. I tried several ugly workarounds and no one helps - I can make fullscreen video smaller but not larger like size is blocked inside video displaing surface code.

**Comment by dashriprock007** [comment]
Thanks for trying!!

Sent from Nine<http://www.9folders.com/>
________________________________
