### ISSUE TITLE
cannot input anything,it's really a fine app?

### ISSUE THREAD

**Issue by aiddroid** [truefedex/tv-bro#104]
when i focus on the url input field，my virtual keyboard pops up，then i scroll down to select character，the url input lost focus！

**Comment by aiddroid** [comment]
please fixed the focus on the element i focued on, auto focus is really a bad idea.

**Comment by greatkeke** [comment]
it's conflict with down narrow, if you just use right or left arrow, it's fine to input the link url.

**Comment by truefedex** [comment]
Probably fixed in v1.8.6 (beta now). Please check (unfortunately I can not reproduce this bug himself on my hardware/emulators)
