### ISSUE TITLE
Text string that can not be translated

### ISSUE THREAD

**Issue by Vladi69** [truefedex/tv-bro#108]
In the file
`res\layout\dialog_favorites.xml`
I found the following string:
`android:text="No bookmarks yet"`

In the file
`res\layout\dialog_new_favorite_item.xml`
I found the following strings:
`android:text="Cancel"`
`android:text="Done"`

Please move it all to
`app\src\main\res\values\strings.xml`

Maybe some more text strings is in the layout files.

**Comment by MailYouLater** [comment]
@Vladi69: It's not exactly true that these "can not be translated" where they are, it's just not as clean or convenient.

Anyway, just because it's possible to translate them where they are doesn't mean that it's desirable to do so.  I do think it would be preferable to move them to `strings.xml`.

Anyway, more importantly, do you have translations you'd like to submit for any of these?  If so, you don't have to wait for them to be migrated to `strings.xml` first, just post the translations here and I'm sure truefedex will be willing to include them.

**Comment by Vladi69** [comment]
I am waiting my commit to be accepted, then when these strings will be integrated in strings.xml I will translate them

**Comment by MailYouLater** [comment]
Why don't you just fix this yourself while you're in there to do the translation?

<table>
<thead>
  <tr>
    <th>Changes to make in string's current location</th>
    <th>Changes to make in strings.xml</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>

https://github.com/truefedex/tv-bro/blob/26721b786a02ff1fed079d5b5d2e342bf73daf53/app/src/main/res/layout/dialog_favorites.xml#L51
```diff
-         android:text="No bookmarks yet"
+         android:text="@string/no_bookmarks_yet"
```

</td>
    <td>

https://github.com/truefedex/tv-bro/blob/26721b786a02ff1fed079d5b5d2e342bf73daf53/app/src/main/res/values/strings.xml#L22-L23
```diff
      <string name="edit">Edit</string>
+     <string name="no_bookmarks_yet">No bookmarks yet</string>
      <string name="new_bookmark">New bookmark</string>
```

</td>
  </tr>
  <tr>
    <td>

https://github.com/truefedex/tv-bro/blob/26721b786a02ff1fed079d5b5d2e342bf73daf53/app/src/main/res/layout/dialog_new_favorite_item.xml#L92
```diff
-             android:text="Cancel"
+             android:text="@string/cancel"
```

</td>
    <td>No need.  This one already exists.

https://github.com/truefedex/tv-bro/blob/26721b786a02ff1fed079d5b5d2e342bf73daf53/app/src/main/res/values/strings.xml#L43

</td>
  </tr>
  <tr>
    <td>

https://github.com/truefedex/tv-bro/blob/26721b786a02ff1fed079d5b5d2e342bf73daf53/app/src/main/res/layout/dialog_new_favorite_item.xml#L100
```diff
-             android:text="Done"
+             android:text="@string/done"
```

</td>
    <td>

https://github.com/truefedex/tv-bro/blob/26721b786a02ff1fed079d5b5d2e342bf73daf53/app/src/main/res/values/strings.xml#L24-L25
```diff
      <string name="title">Title</string>
+     <string name="done">Done</string>
      <string name="url" translatable="false">URL</string>
```

</td>
  </tr>
</tbody>
</table>

**Comment by MailYouLater** [comment]
@Vladi69: I made the changes, submitted a pull request (#129), and truefedex has accepted it in the `develop` branch, so there should be nothing to prevent you from adding your translations of these strings now.

**Comment by MailYouLater** [comment]
Since #129 moved these strings to `strings.xml` as requested, and #130 added the Italian translations which Vladi69 opened this issue to be able to add, I think this issue can be closed now.
