### ISSUE TITLE
[FR] option to copy link on long pressing link

### ISSUE THREAD

**Issue by mrx23dot** [truefedex/tv-bro#112]
When I long press a link popup should contain "copy link", 
otherwise it takes a lot of steps to get the url on android TV.

Opera browser also has option to "copy text" too.

**Comment by truefedex** [comment]
Implemented in v1.8.6
https://github.com/truefedex/tv-bro/releases/tag/v1.8.6

**Comment by truefedex** [comment]
@mrx23dot this may mean that what you click is actually not a link, but an element which has an onclick event handler that is processed by a java script.
