### ISSUE TITLE
Full incognito support

### ISSUE THREAD

**Issue by shark-yn** [truefedex/tv-bro#119]
I plan to add full incognito support to the browser, saving nothing at all for incognito mode.

The current design is saving temp history and clear when exit, though there might be case where app is not properly exited (power outage). Though before I start, want to know whether the current design is intended for some other reasons I might missed.

**Comment by truefedex** [comment]
Hi @shark-yn 

Currently tvbro trying to isolate and remove any data stored by webview in incognito mode. Not only history. 
See MainActivityViewModel.prepareSwitchToIncognito.

**Comment by shark-yn** [comment]
Hi @truefedex ,

I am aware that tvbro will try to remove history in incognito mode at [exit or toggle](https://github.com/shark-yn/tv-bro/blob/7ad9bfe521afc2728e7c962368122627b6fac620/app/src/main/java/com/phlox/tvwebbrowser/activity/main/MainActivity.kt#L724-L724), though it still saves [temporary history items into DB](https://github.com/shark-yn/tv-bro/blob/7ad9bfe521afc2728e7c962368122627b6fac620/app/src/main/java/com/phlox/tvwebbrowser/activity/main/MainActivity.kt#L128-L128). I think incognito means we should avoid saving any history at first place, instead of saving temporary histories and removing them at exit (what if the app is not properly exited? The next person who opens the app might the see the incognito history). Though before I make the change, I want to know whether there is any other intention to save the temporary incognito history

**Comment by truefedex** [comment]
I agree with you @shark-yn - saving temporary browsing history in incognito mode can be turned off, as other browsers don't seem to save it even temporarily.

**Comment by truefedex** [comment]
Fixed in release (please reopen if not):
https://github.com/truefedex/tv-bro/releases/tag/v1.8.5
