### ISSUE TITLE
Allow switching tabs with mouse click.

### ISSUE THREAD

**Issue by MailYouLater** [truefedex/tv-bro#12]
I have a mouse connected to my Android TV device, and TV Bro seems to work pretty well with it, but I can't switch tabs by clicking with the mouse. I have to click and drag, as if I'm swiping with my finger on a touchscreen.  This is doable, but awkward, and unintuitive, to the point that I didn't realize I could switch tabs with the mouse at all for quite some time and was picking up my remote to switch tabs with the D-pad.

Please allow clicking to switch tabs.  Thank you.

**Comment by truefedex** [comment]
Implemented. Please, check v1.5.8 (available in beta channel).

**Comment by MailYouLater** [comment]
Hey, sorry for taking so long to get back to you, but I just wanted to say thank you for implementing my suggestion. 😄
