### ISSUE TITLE
Cannot access download folder on Google TV Android 12

### ISSUE THREAD

**Issue by jihooyoon** [truefedex/tv-bro#124]
Device: Chromecast with Google TV
AndroidTV Ver: 12

It seems that download folder of TVBro is set to default app folder (inside Internal Storage/Android/data/...) instead of Internal Storage/Download. 
This makes download folder of TVBro become inaccessible by file managers, because on AndroidTV 12, access to Android/data/... from file managers is locked by OS, and loophole workaround doesn't work

**Comment by truefedex** [comment]
Fixed in release (please reopen if not):
https://github.com/truefedex/tv-bro/releases/tag/v1.8.5
