### ISSUE TITLE
Android 4.1/4.2 compatibility

### ISSUE THREAD

**Issue by mrx23dot** [truefedex/tv-bro#131]
I still come across many android TVs that run **v4.1/4.2 android**, (usually they are way behind of smartphones)

Would it be lot a of work to add compatibility?

**Comment by truefedex** [comment]
Sorry, but tvbro developed by very limited amount of peoples on their spare time. We already supporting 10 different android API levels (Android 6.x-13.x). Support for more legacy versions of android will mean a complete halt to new feature development.
