### ISSUE TITLE
I have to force stop every time I want to watch a new video

### ISSUE THREAD

**Issue by steamedham544** [truefedex/tv-bro#132]
Chromecast with Google TV Android 12

It's like closing the tab doesn't release the media player. I'm watching a stream and wheni want to find a new one, the new stream pauses after a few seconds as if the old stream is playing. I have to force close the app every single time. It's so annoying.

**Comment by MailYouLater** [comment]
I've experienced a similar problem before which I think stems from the same issue.

Specifically, I was checking out a site (I don't remember what site) that was mentioned in another TV Bro GitHub issue, one that was supposed to offer access to live TV streams, and I don't remember exactly what I did at the time, so I can't offer exact steps to reproduce the issue, but I ended up in a situation where the tab containing the video player had been closed, but the audio from it was still playing, and if I tried playing another video with a different app, it would stop after a second or two, and the audio from TV Bro would come back.  I had to Force stop TV Bro to get the audio to stop playing, then was able to watch videos in other apps again.

**Comment by Daddy7x6** [comment]
I've had similar experiences - on a few occasions, audio from a video has continued even after exiting TVbro. I suspect the video app hasn't been killed correctly.
Also, my "clean-up" app shows a big increase in running apps after TVbro has been used.
