### ISSUE TITLE
Full Screen Fix

### ISSUE THREAD

**Issue by goncalo18s** [truefedex/tv-bro#145]
For those who have problems with full screen not working do this:, 
Since Android System WebView v109.xxx.x.xxxx, TV Bro full screen stopped working, but you can fix it, just do this:
(tested in xiaomi mi box s)

1- **Unninstal Android System WebView**, just go "all apps" and press "unninstall updates";

2- Get the Android System [WebView v108.0.5359.128](https://www.apkmirror.com/apk/google-inc/android-system-webview/android-system-webview-108-0-5359-128-release/), this is the most updated version before v109. 
Chose **APK ONLY**, not the bundle pack, and **choose your android version** and the correct **architecture type** of your device, if you don't know this specs from your device, just search in google it;
(I tried as well Android System WebView 110.0.5481.64 but doesn't work, maybe they fix it in the future...)

3- Use a pen drive to install the apk or just download it from the tv bro browser and using a file manager (you can download it on playstore) to install the apk;

4- Done! In the end you check everything, go to TV bro "Version & Updates" tab, and check, if it's okey, it will show:
Version: 1.8.6
com.google.android.view:108.0.5359.128

**Comment by dungInte** [comment]
I think just only do step 1 uninstall update Android System WebView . Then reinstall TVBro or remove data in app.

**Comment by truefedex** [comment]
Chromium team already made [fix ](https://bugs.chromium.org/p/chromium/issues/detail?id=1411583) and seems this fix already available in [Android WebView Canary v101.0.4951.74](https://play.google.com/store/apps/details?id=com.google.android.webview.canary&hl=en&gl=US):
I dont recommend users to install WV Canary - it is updated too often and may be buggy in other aspects. 
But the fact that the fix appeared in Canary means that it will soon (up to month) appear in the stable version.

**Comment by goncalo18s** [comment]
> I think just only do step 1 uninstall update Android System WebView . Then reinstall TVBro or remove data in app.

but like this you can use it Android System WebView updated for other apps and don't use the stock one..

> Chromium team already made [fix ](https://bugs.chromium.org/p/chromium/issues/detail?id=1411583) and seems this fix already available in [Android WebView Canary v101.0.4951.74](https://play.google.com/store/apps/details?id=com.google.android.webview.canary&hl=en&gl=US): I dont recommend users to install WV Canary - it is updated too often and may be buggy in other aspects. But the fact that the fix appeared in Canary means that it will soon (up to month) appear in the stable version.

let's see, maybe they fix it n v111.x.xxx, for now is just beta so i didn't test it

**Comment by MailYouLater** [comment]
> ... seems this fix already available in [Android WebView Canary v101.0.4951.74](https://play.google.com/store/apps/details?id=com.google.android.webview.canary&hl=en&gl=US)

I'm guessing that was supposed to be 110.x or 111.x (M111 was mentioned, so probably 111.x)...  
I see that WebView Canary is now in 112.x versions, so the fix should be included...  
I would try it to test the fix (as I tested 109.x) but none of the ways to try early WebView releases seem to work right right for me on Android TV 9... 😞

**Comment by C64C128** [comment]
Can someone explain if this fix also works on a Firestick 4k?

How can one "Unninstal Android System WebView" - I do not find such a component.

Thanks for help.

**Comment by truefedex** [comment]
> Can someone explain if this fix also works on a Firestick 4k?
> 
> How can one "Unninstal Android System WebView" - I do not find such a component.
> 
> Thanks for help.

Unfortunately, most likely not. Firestick has other known issues with fullscreen video in webview.
I'm currently investigating the possibility of porting tvbro to GecoView. If it succeeds, it will fix this and many other problems that WebView brings.

**Comment by C64C128** [comment]
Sounds promising... nevertheless I appreciate your nice work!

**Comment by Quikfix73** [comment]
My MiBox had an update to Android System WebView version 111.0.5563.58 today and I updated and tested it and the full screen is working again.

**Comment by truefedex** [comment]
@Quikfix73
I tried it on a Nvidia Shield TV (2015) and it still seems to have problems - fullscreen only works the first time, but all subsequent times it still doesn't work.

**Comment by Quikfix73** [comment]
That's interesting as I tested it on a few sites multiple times and it works consistently for me.

**Comment by AitoZ** [comment]
@truefedex I think you can close this issue, it seems to be fixed with version **113.0.5672.76** at least it's the case on my Mi Box.
