### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by mpaunovic** [truefedex/tv-bro#153]
Could someone please update README.md with some info about the latest GeckoView based TV Bro alpha release? This could be useful because more people would know about the release and more people would test it, submitting potential issues they have encountered.

Thank you.

**Comment by truefedex** [comment]
This is now only an alpha release (in fact, even more like an early preview). Now there are many more problems that I know about. I would not want people to start writing a lot about bugs at this stage. I hope soon I will fix a few very serious bugs and publish a version in the beta channel. After that, it's probably worth changing the readme.

**Comment by mpaunovic** [comment]
OK, sounds good to me.  Thank you for the answer and your hard work.
