### ISSUE TITLE
ad blocker doesnt work

### ISSUE THREAD

**Issue by tomtom38** [truefedex/tv-bro#174]
**Describe the bug**
The ad blocker icon count block elements but on the screen are a lot of popups and so on

**To Reproduce**
1. Go to 'bs.to
2. Click on 'choose any series and try to start the video
4. *you a lot off ads that you have to close

**Expected behavior**
I think a ad blocker like  u block is the right answer

**Screenshots**

**Environment (please complete the following information):**
 - android tv latest
 -chromcast with google tv HD
 - TV Bro version latest
 - bs.to

**Comment by the-badmannn** [comment]
I just noticed that pop-up blocker it's not working at all with android webview option selected, it only works with geckoview..., but still some of the normal "in page" ads are shown..
