### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by Darin755** [truefedex/tv-bro#189]
As you might be aware, there hasn't been a commit since May. Furthermore there are a bunch of dead issues and multiple pull requests waiting to be merged without comments on them.

What's the status of this project?

**Comment by PeterNjeim** [comment]
It's still getting updates I'm pretty sure, just now on the Google Play Store and no longer committing to GitHub, so it went closed-source

**Comment by PeterNjeim** [comment]
Ignore that comment I made, I was wrong

**Comment by truefedex** [comment]
Hi @Darin755 

This project suspended. 
Unfortunately, I don’t have time to work on it right now. But I still plan to return to it after some time. There have already been periods in the history of TV Bro when there were no updates even for several years 😑 But now I hope that I will be able to continue development over the next six months.
I'm sorry for keeping people waiting.

**Comment by Darin755** [comment]
> Hi @Darin755
> 
> This project suspended. Unfortunately, I don’t have time to work on it right now. But I still plan to return to it after some time. There have already been periods in the history of TV Bro when there were no updates even for several years 😑 But now I hope that I will be able to continue development over the next six months. I'm sorry for keeping people waiting.

All good, I just think you should state this somewhere in the readme. Web browser tech moves fast and needs peoples time. Working on this in your free time is all well and dandy as long as you let people know. 

Thank you for what your doing

**Comment by PeterNjeim** [comment]
Why would the readme need to state that there aren't any updates for a few months? You can look at the latest commit for that. People should still be making issues so that when development continues, bugs can be fixed

**Comment by truefedex** [comment]
I think it’s better I’ll try to set aside time to make a minor update with the most simple fixes, integration of pull requests and updating dependencies soon.
I think this will be better than a line in Readme to indicate that the project is not abandoned.
