### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Jsinnnn** [truefedex/tv-bro#201]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS version: [e.g. Android TV 10]
 - Device [e.g. NVidia Shield Pro 2015]
 - TV Bro version [e.g. v1.8.1]
 - URL or domain name where problem can be reproduced [optional, e.g. https://google.com]

**Additional context**
Fix

**Comment by truefedex** [comment]
@Jsinnnn Do you plan to add something there? This one looks like empty. Will delete it then
