### ISSUE TITLE
From GP feedback: "Constantly get the message: "android.webkit.resource.protected media_id" DENY, ALLOW"

### ISSUE THREAD

**Issue by truefedex** [truefedex/tv-bro#23]

**Comment by lukenzo** [comment]
Any updates on this ? I keep getting "This web page wants to use following resources: android.webkit.resource.PROTECTED_MEDIA_ID" when trying to play video. Deny/Allow does nothing.

**Comment by gergor888** [comment]
I am getting similar issue. Got the same pop-up about android.webkit.resource.protected media_id over the video, if I click either "deny" or "allow", the screen goes black and I continue to hear audio.

Example of videos can be found here: https://www.wimbledon.com/en_GB/video/index.html

**Comment by davidmoy** [comment]
Any suggestion as to when this bug will be fixed? I love the app, but this slight limitation is frustrating 😔
