### ISSUE TITLE
Use bigger list of domains

### ISSUE THREAD

**Issue by komawoyo** [truefedex/tv-bro#29]
Hi, there's a bunch of website that still have tons of ads using the default yoyo list. Can we have an updated apk with  https://oisd.nl/?p=dl domain list?

**Comment by truefedex** [comment]
Hi. There are almost ready new alpha with [easylist ](https://easylist.to/) usage integrated. It is shows more adwanced blocking. I think it wiil be ready this week.

**Comment by truefedex** [comment]
Now it is in beta and soon will be in release channel.
