### ISSUE TITLE
Video full-screen issue

### ISSUE THREAD

**Issue by sglemon** [truefedex/tv-bro#31]
video doesn't get fullscreen on clicking full screen it just gets shifted to left corner and rest of the screen is complete black.
this is how it looks on full-screen:-
![1616511527698-1314215371](https://user-images.githubusercontent.com/81247767/112167398-6bc25880-8c16-11eb-87b2-79a50a8a2662.jpg)
any ways I like that the apps interface is very clean.

**Comment by truefedex** [comment]
Is this on Fire Stick 4K?
There are already similar issue: https://github.com/truefedex/tv-bro/issues/24

**Comment by sglemon** [comment]
> Is this on Fire Stick 4K?
> There are already similar issue: https://github.com/truefedex/tv-bro/issues/24

Yes it is on firestick

**Comment by sglemon** [comment]
But is it resolved

**Comment by truefedex** [comment]
Unfortunately no. TV Bro does not do much with video now - it just uses built-in system webview capabilities.
