### ISSUE TITLE
History is broken in 1.6.0 Alpha 2

### ISSUE THREAD

**Issue by MailYouLater** [truefedex/tv-bro#34]
After updating from 1.6.0 to 1.6.0 Alpha 2, I can no long er see my history.  I have been to several sites, hit the Clear buton, exited & restarted TV Bro, and also tried rebooting my Android TV box (browsing a bit after each) but the history is always empty, with nothing but the Clear button on the screen.

![Screenshot of TV Bro 1.6.0 Alpha 2 not showing any history when there should be some](https://i.postimg.cc/bNqTYDYw/Screenshot-20210330-150124.png)

**Comment by PSTrophy** [comment]
Downloads in progress also show no size or progress just a spinning circle.

**Comment by truefedex** [comment]
@PSTrophy this is normal. Not all servers provide downloads size/progress info.

**Comment by MailYouLater** [comment]
I don't know about PSTrophy's comment, but I can confirm that updating to 1.6.1 fixed the history issue this thread was actually about.

Thank you truefedex!
