### ISSUE TITLE
Option to keep screen on / disable screensaver

### ISSUE THREAD

**Issue by istvanmate** [truefedex/tv-bro#47]
Using tv-bro on a Hyunday TV. It is working perfectly. However the Hyunday android version has a screensaver with no option to turn it off, so the TV screen turns off every 2 hours... Already contacted Hyunday about it, no response from their side... Is it possible to have an option to keep the screen always on?

**Comment by truefedex** [comment]
TV Bro already asks operating system to keep screen on during fullscreen video playback. Are you mean you want it to have an option to keep screen on even during regular web browsing?

**Comment by istvanmate** [comment]
Yes.

**Comment by truefedex** [comment]
@sebiniemann Of course, you can help with this. Thank you in adwance!

**Comment by MailYouLater** [comment]
This functionality is included in version 1.8, I have tested it and it worked as expected.
