### ISSUE TITLE
Can’t delete from home page

### ISSUE THREAD

**Issue by ShadwDrgn** [truefedex/tv-bro#48]
Every browser I’ve ever used except this one lets you remove pages from the homepage. Even clearing my history doesn’t remove pages seemingly. I can’t even force new pages to appear there to get existing ones to drop off. Is there something I’m missing?

**Comment by UdaySriHarsha** [comment]
Maybe cache and forces top helps(after history cleaning)

**Comment by MailYouLater** [comment]
I've found that if I remove all visits to a particular page from my history, then exit TV Bro, the next time I open it, that page is no longer among the recommendations presented on the home/new-tab page.
