### ISSUE TITLE
Downloading Broken on Chromecast with Google TV

### ISSUE THREAD

**Issue by f1vefour** [truefedex/tv-bro#55]
I installed the latest TV Bro (v1.6.1) on my Chromecast with Google TV by way of downloading it to my phone and pushing it using X-plore file manager wifi sharing function.

After installing I tried to download several zip files from different places including GitHub and they all failed. I use TV Bro on my H8G Android TV and downloading works great.

I got the same results using the Downloader app which can be found on Google Play.

It may be a limitation Google has imposed in WebView?

**Comment by truefedex** [comment]
It is possible, or Google may change some internal behavior of webview. I should check.

**Comment by dmemarko** [comment]
Got the same issue on Google Chromecast. Couldn't it be a permission issue?

**Comment by truefedex** [comment]
Possible. I not checked TV Bro long time especially on new android tv versions. May be it is time to check)

**Comment by f1vefour** [comment]
I appreciate you looking into it. There is not a better browser for the power user than TV Bro.

**Comment by f1vefour** [comment]
I'm closing this issue as I was somehow mistaken on the version I was running.

I went to TV Bro settings > Version & Updates and it showed I was running v1.6.0 with the v1.6.1 update available. After updating to v1.6.1 downloads are indeed working.

Sorry for the confusion.

**Comment by dmemarko** [comment]
I’m running 1.6.1 and download starts but file is never created in Download folder.

**Comment by f1vefour** [comment]
I did update WebView today, make sure yours is up to date.
