### ISSUE TITLE
Private tabs

### ISSUE THREAD

**Issue by inoyakaigor** [truefedex/tv-bro#6]
С любым ограничением можно свыкнуться, но без приватных вкладок жить тяжко. Есть ли планы когда-либо их внедрить?

**Comment by truefedex** [comment]
Сейчас разработка не ведется. Но если еще продолжу, то приватные вкладки будут добавлены в список  "что сделать".

**Comment by MailYouLater** [comment]
Private/Incognito browsing has been in the last few releases, starting with v1.8.2.  This issue should be closed.
