### ISSUE TITLE
Clear history on exit 

### ISSUE THREAD

**Issue by killerz298** [truefedex/tv-bro#61]
I don't need my history and tabs saved after browsing. Can an option be added which clears tabs and history upon closing the app so that it starts fresh.

**Comment by truefedex** [comment]
There planned an "incognito" mode for this soon.

**Comment by killerz298** [comment]
Great news, I look forward to it!

**Comment by jhedfors** [comment]
Yes. I seem to have issues with streams pausing after a second or so when multiple tabs are open. Closing the tabs seems to help this.

**Comment by truefedex** [comment]
v1.8.1 (currently beta) incognito mode implemented; Also there are button in settings to clear web cache. I think this should help to deal with this problem.
@jhedfors regarding streams pausing I think other browsers not auto-pausing streams too while user switching tabs. But I plan to investigate this deeper soon. May be TV Bro though have some issues here too.
