### ISSUE TITLE
cannot enter url / no menu at all accessible

### ISSUE THREAD

**Issue by Auncaughbove17** [truefedex/tv-bro#64]
When I open the app on my Mi Box S (installed from play or sideloaded), I only see this. I can navigate the displayed websites, but no matter what buttons I press or where I  move the cursor I'm unable to access some menu to enter an url or something. Am I doing something wrong?
![image](https://user-images.githubusercontent.com/26165288/148653645-9fb6dd97-c85f-4d3a-b228-9c802d1d93a1.png)

**Comment by E-D-W-I-N** [comment]
I'm using Mi Box S as well. Have you tried pressing back button on your remote? This shows menu buttons, at least for me...

**Comment by Auncaughbove17** [comment]
Ah that does it my bad. I was certain I tried that. Thanks!
