### ISSUE TITLE
No more space inside settings layout

### ISSUE THREAD

**Issue by E-D-W-I-N** [truefedex/tv-bro#73]
After a recent pull request #72 from [sebiniemann](https://github.com/sebiniemann) I've noticed the problem with `view_settings_main.xml`. We're almost out of space with settings options inside main settings tab. The next setting just won't fit on the screen.

I guess it's time to add a `ScrollView` or even some kind of `RecyclerView` with custom adapter. Because all of the setting's view a pretty similar (Switch, DropDown, etc.) feels like `RecyclerView` approach will be the best one.

![Screenshot_20220215_092904](https://user-images.githubusercontent.com/22594525/153981335-fc41406e-5f41-4fef-baca-5d352bb87a8b.png)

**Comment by truefedex** [comment]
@E-D-W-I-N MainSettingsView already is ScrollView and it scrolls pretty well. No need recyclerview there.
In future settings dialog may be replaced by fullscreen window so there will be more space but currently it is ok to leave it as is.
