### ISSUE TITLE
Any way to watch udemy courses with it

### ISSUE THREAD

**Issue by andreescocard** [truefedex/tv-bro#83]
I tried to watch a couse but asked me to allow a resource of protected media id, and when i try to play it, nothing happens. Any solution for this?

**Comment by truefedex** [comment]
Please provide some link to page where problem occurs or at least link to website. This can help to debug the problem.

**Comment by andreescocard** [comment]
The website link: https://www.udemy.com/
I have logged in and was trying to watch a course i bought, but with no success.

**Comment by truefedex** [comment]
Looks like this is problem with DRM support by your device. I checked TV Bro on different DRM contents and found that some devices plays them without problem while other not. There are seems several Wideline DRM support levels and some content require highest level - L1. You can read about this here:
https://indianexpress.com/article/technology/techook/widevine-drm-what-it-is-and-what-version-does-your-phone-support-7499370/
In any case looks like there is nothing to do with this on TV Bro’s side unfortunately.
