### ISSUE TITLE
Search/Link Bar keeps on disappearing when typing

### ISSUE THREAD

**Issue by httpapb** [truefedex/tv-bro#84]
Title says it all. It only allows me to type 3 letters then after that, it'll disappear? I already uninstalled then installed it twice but it's still happening.

**Comment by truefedex** [comment]
In v1.8.1(beta) Searchbar layout are changed a bit. Is this issue still reproducible?
Do you use standart tv remote to input letters or some phisical keyboard?

**Comment by httpapb** [comment]
Yes and I'm using standard tv remote to input letter 😅

**Comment by heinnovator** [comment]
Try this keyboard

https://www.apkmirror.com/apk/google-inc/leanback-keyboard/leanback-keyboard-1-0-2-2423292-release/leanback-keyboard-1-0-2-2423292-android-apk-download/

**Comment by truefedex** [comment]
Probably fixed in v1.8.6 (beta now). Please check (unfortunately I can not reproduce this bug himself on my hardware/emulators)
