### ISSUE TITLE
Block popups 

### ISSUE THREAD

**Issue by aaref1234** [truefedex/tv-bro#95]
Please add a popup blocker .

**Comment by MailYouLater** [comment]
There was some discussion about popup blockers on Issue #37.  Here's my thoughts on what I'd like to see in a popup blocker implemented in TV Bro.

> I've used a couple of browsers with popup blocking similar to what I'd like to see in TV Bro.
> In one of the Android TV browsers (which I don't use because of other issues) it pops up a dialogue box to ask if you want to open the popup (with No preselected so that you're less likely to accidentally open an unwanted popup:
> ![Screenshot_Puffin TV Browser](https://user-images.githubusercontent.com/1279475/155423247-c9f6a590-b790-43eb-be7c-e3558106e62a.png)
> In an app I sometimes use to cast content from my phone to a TV (usually only when other options aren't working for me) it briefly pops up a bar at the bottom of the screen to notify the user that a popup has been blocked, along with a button to open the popup instead.
> ![Screenshot_Cast to TV-XCast](https://user-images.githubusercontent.com/1279475/155423295-2812010a-15ed-4544-b3fe-d17a866a9c63.jpg)
> 
> I think it would be really nice if TV Bro used a bar that doesn't cover too much of the page's content when open, and if possible dismissed itself if the user doesn't interact with it after a set periood of time, even better (for me at least) if the bar is at the top so it's less likely to cover subtitles.  But even if it's just a big dialogue box that blocks half the screen until you manually choose if you want to block or allow the popup, it would still be better than opening the popup, after which the user has to open & navigate the menu to close it and go back to the tab they were on.
> 
> _Originally posted by @MailYouLater in https://github.com/truefedex/tv-bro/issues/37#issuecomment-1049334683_

**Comment by aaref1234** [comment]
Hi .

Please add the previous suggestion .

As well as adding a shortcut to close the current tab due to popups .

Thank you .

**Comment by WIStudent** [comment]
I suggest adding a new button besides the existing adblocker button that allows to enable/disable the blocking of popups. Unlike ads, popups should be allowed per default. I opened a [pull request](https://github.com/truefedex/tv-bro/pull/125) showing how this could look like.

**Comment by truefedex** [comment]
Based on @WIStudent suggestions and MR and my foundings about how new windows created in webview added additional button near adblocker toggle button. This allows to select popup blocking behaviour for particular host. Default is to block any new tabs, windows and dialogs that is not user-initiated. May be in future there should be additional setting to set default behaviour somewhere in app's settings.

**Comment by MailYouLater** [comment]
Well... In its current state, it defaults to blocking the things I want and allowing the things I don't.  I have to set it to not block anything to be able to delete the edit history on a GitHub comment where I made a typo, but I need it set to block everything to stop new tabs from opening when I try to push play on a video.

I really appreciate the popup notification that appears at the bottom right of when it blocks something, but I really wish it also had a button to let me allow it just this one time, so I could leave it set to block everything all the time and only manually allow things I want when they occur.

**Comment by truefedex** [comment]
>but I really wish it also had a button to let me allow it just this one time
I agree, but this is problematic to implement - you need to remember that some sites spam with new windows and windows are of different types, and messages can be of different types, and if you automatically redirect the user's input focus to popup "notification", then this may not give the user the opportunity to do what something on the page. And if you do not redirect the user's focus to the pop-up notification, then another question arises - how then can the user move the focus there on their own.
